from dataclasses import dataclass
from typing import Tuple


@dataclass(frozen=True)
class ConversationTurn:
    user_input: str
    expected_result: str
    assert_paths: Tuple[str, ...] = ()
    assert_structure: Tuple[str, ...] = ()
    assert_semantics: Tuple[str, ...] = ()
    assert_safety: Tuple[str, ...] = ()
    forbidden_behavior: Tuple[str, ...] = ()


@dataclass(frozen=True)
class ValidationCase:
    case_id: str
    skill: str
    layer: str
    fixture: str
    prompt: str
    purpose: str
    expected_result: str
    assert_paths: Tuple[str, ...] = ()
    assert_structure: Tuple[str, ...] = ()
    assert_semantics: Tuple[str, ...] = ()
    assert_safety: Tuple[str, ...] = ()
    forbidden_behavior: Tuple[str, ...] = ()
    turns: Tuple[ConversationTurn, ...] = ()


def vcase(
    case_id: str,
    skill: str,
    layer: str,
    fixture: str,
    prompt: str,
    purpose: str,
    expected_result: str,
    *,
    assert_paths: Tuple[str, ...] = (),
    assert_structure: Tuple[str, ...] = (),
    assert_semantics: Tuple[str, ...] = (),
    assert_safety: Tuple[str, ...] = (),
    forbidden_behavior: Tuple[str, ...] = (),
    turns: Tuple[ConversationTurn, ...] = (),
) -> ValidationCase:
    return ValidationCase(
        case_id=case_id,
        skill=skill,
        layer=layer,
        fixture=fixture,
        prompt=prompt,
        purpose=purpose,
        expected_result=expected_result,
        assert_paths=assert_paths,
        assert_structure=assert_structure,
        assert_semantics=assert_semantics,
        assert_safety=assert_safety,
        forbidden_behavior=forbidden_behavior,
        turns=turns,
    )


SETUP_ARCHITECT_CASES = (
    vcase(
        "SA-01",
        "setup-architect",
        "流程场景层",
        "empty-project",
        "在空仓库中请求执行 setup-architect 初始化默认架构框架。",
        "锁定最基础的 setup 成功路径",
        "SUCCESS_INIT",
        assert_paths=(
            ".architecture/technical-solutions/",
            ".architecture/templates/",
            ".architecture/templates/technical-solution-template.md",
            ".architecture/members.yml",
            ".architecture/principles.md",
        ),
        assert_structure=(".architecture 最小结构完整",),
        assert_safety=("只创建最小必需结构",),
        forbidden_behavior=("写入 legacy 路径",),
    ),
    vcase(
        "SA-02",
        "setup-architect",
        "流程场景层",
        "complete-architecture-default-template",
        "在已完成初始化的仓库中再次请求执行 setup-architect 完整安装流程。",
        "防止重复 setup 产生重复目录和副产物",
        "SUCCESS_INIT",
        assert_paths=(".architecture/",),
        assert_structure=("不生成 .architecture/.architecture", "不生成重复模板"),
        assert_safety=("不引入 legacy 或临时副产物",),
        forbidden_behavior=("嵌套 .architecture", "重复模板副本"),
    ),
    vcase(
        "SA-03",
        "setup-architect",
        "行为回归层",
        "partial-architecture-missing-one-file",
        "在只缺少一个必需文件的已部分初始化仓库中请求补齐 setup。",
        "只补缺失项，不覆盖已有项",
        "SUCCESS_INIT",
        assert_paths=(
            ".architecture/members.yml",
            ".architecture/principles.md",
            ".architecture/templates/technical-solution-template.md",
        ),
        assert_structure=("现有文件保持原位",),
        assert_safety=("仅补齐缺失的单个前置文件，已有内容不被无提示覆盖",),
        forbidden_behavior=("重写无缺失文件",),
    ),
    vcase(
        "SA-04",
        "setup-architect",
        "行为回归层",
        "complete-architecture-default-template",
        "初始化流程询问模板定制时，用户明确回答保留当前模板。",
        "用户拒绝定制模板时保留当前模板",
        "SUCCESS_INIT",
        assert_paths=(".architecture/templates/technical-solution-template.md",),
        assert_structure=("模板路径不变",),
        assert_semantics=("模板最终状态明确为保留当前模板",),
        assert_safety=("不发生模板替换",),
        forbidden_behavior=("无用户请求时覆盖模板",),
    ),
    vcase(
        "SA-05",
        "setup-architect",
        "行为回归层",
        "template-replacement-inputs",
        "完整初始化结束后，用户提供完整 Markdown 模板并要求替换当前模板。",
        "初始化尾声允许整文件替换模板",
        "SUCCESS_REPLACE_TEMPLATE",
        assert_paths=(".architecture/templates/technical-solution-template.md",),
        assert_structure=("整体替换单个目标文件",),
        assert_safety=("不做局部 merge",),
        forbidden_behavior=("局部编辑", "内容合并"),
    ),
    vcase(
        "SA-06",
        "setup-architect",
        "行为回归层",
        "complete-architecture-default-template",
        "安装完成后单独请求替换 `.architecture/templates/technical-solution-template.md`。",
        "安装后仅替换模板时跳过完整 setup",
        "SUCCESS_REPLACE_TEMPLATE",
        assert_paths=(".architecture/templates/technical-solution-template.md",),
        assert_structure=("只走模板替换分支",),
        assert_safety=("不重跑初始化流程",),
        forbidden_behavior=("重新安装 .architecture 基础结构",),
    ),
    vcase(
        "SA-07",
        "setup-architect",
        "对抗边界层",
        "partial-architecture-missing-one-file",
        "在缺少模板目录、模板文件、成员文件或原则文件之一时，请求只执行模板替换分支。",
        "模板替换前置不满足时必须停机",
        "STOP_AND_REDIRECT",
        assert_paths=(
            ".architecture/templates/",
            ".architecture/templates/technical-solution-template.md",
            ".architecture/members.yml",
            ".architecture/principles.md",
        ),
        assert_semantics=("响应明确点名缺失的前置路径",),
        assert_safety=("要求先完成完整 setup", "不静默补文件"),
        forbidden_behavior=("边补环境边替换模板",),
    ),
    vcase(
        "SA-08",
        "setup-architect",
        "对抗边界层",
        "template-replacement-inputs",
        "用户仅提供模板片段、patch 或口头描述并要求替换技术方案模板。",
        "拒绝模板片段和口头描述输入",
        "STOP_AND_ASK",
        assert_semantics=("继续索要完整 Markdown、路径或链接",),
        assert_safety=("不自动生成模板", "不做局部编辑", "不做内容合并"),
        forbidden_behavior=("根据片段脑补完整模板",),
    ),
    vcase(
        "SA-09",
        "setup-architect",
        "行为回归层",
        "complete-architecture-default-template",
        "用户请求自定义成员配置，并尝试加入新的专家角色。",
        "成员定制必须保留核心成员",
        "SUCCESS_INIT",
        assert_semantics=(
            "保留系统架构师",
            "保留领域专家",
            "保留安全专家",
            "保留性能专家",
            "保留可维护性专家",
        ),
        assert_safety=("允许增补专家，不允许替换核心成员",),
        forbidden_behavior=("删除核心成员",),
    ),
    vcase(
        "SA-10",
        "setup-architect",
        "行为回归层",
        "complete-architecture-default-template",
        "用户请求自定义架构原则，并希望调整团队的评审与决策准则。",
        "原则定制必须保留核心原则和最低覆盖范围",
        "SUCCESS_INIT",
        assert_semantics=(
            "保留核心原则",
            "覆盖模块边界与依赖方向",
            "覆盖 API / 事件 / 数据边界",
            "覆盖测试和验证基线",
            "覆盖安全与合规底线",
            "覆盖技术方案和实施计划的决策标准",
        ),
        assert_safety=("不删除核心原则",),
        forbidden_behavior=("删除核心原则",),
    ),
    vcase(
        "SA-11",
        "setup-architect",
        "静态契约层",
        "complete-architecture-default-template",
        "setup-architect 完成初始化并准备输出最终总结。",
        "最终总结前结构必须已验证",
        "SUCCESS_INIT",
        assert_paths=(
            ".architecture/technical-solutions/",
            ".architecture/templates/",
            ".architecture/templates/technical-solution-template.md",
            ".architecture/members.yml",
            ".architecture/principles.md",
        ),
        assert_safety=("无 legacy 目录",),
        forbidden_behavior=(
            "保留 .architecture/solutions",
            ".architecture/plans",
            ".architecture/reviews",
        ),
    ),
    vcase(
        "SA-12",
        "setup-architect",
        "静态契约层",
        "empty-project",
        "在空仓库中执行 setup-architect，检查初始化过程是否引入无关文件或目录。",
        "安装和初始化不应引入无关产物",
        "SUCCESS_INIT",
        assert_structure=("assistant 目标目录唯一",),
        assert_safety=("无 CLAUDE.md", "无 agent_docs", "无嵌套 .git", "无随机 temp 目录"),
        forbidden_behavior=("生成无关安装副产物",),
    ),
    vcase(
        "SA-13",
        "setup-architect",
        "流程场景层",
        "complete-architecture-default-template",
        "setup-architect 初始化后进入模板定制确认对话。",
        "验证多轮确认后可保留当前模板",
        "SUCCESS_INIT",
        assert_semantics=("先确认是否需要定制模板",),
        assert_safety=("未确认前不直接输出最终总结",),
        forbidden_behavior=("未确认模板策略就直接给出最终总结",),
        turns=(
            ConversationTurn(
                user_input="先完成 setup-architect 初始化，模板部分你先别直接定，先问我要不要自定义。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("询问是否需要自定义模板",),
                assert_safety=("暂停等待模板决策",),
                forbidden_behavior=("直接输出最终总结",),
            ),
            ConversationTurn(
                user_input="不用自定义，保持当前模板即可。",
                expected_result="SUCCESS_INIT",
                assert_paths=(".architecture/templates/technical-solution-template.md",),
                assert_semantics=("模板最终状态明确为保留当前模板",),
                assert_safety=("不发生模板替换",),
                forbidden_behavior=("无用户请求时覆盖模板",),
            ),
        ),
    ),
    vcase(
        "SA-14",
        "setup-architect",
        "行为回归层",
        "template-replacement-inputs",
        "setup-architect 初始化后进入模板替换确认对话。",
        "验证多轮确认后可整体替换模板",
        "SUCCESS_REPLACE_TEMPLATE",
        assert_paths=(".architecture/templates/technical-solution-template.md",),
        assert_structure=("整体替换单个目标文件",),
        assert_safety=("不做局部 merge", "未确认前不直接输出最终总结"),
        forbidden_behavior=("局部编辑", "内容合并", "未确认模板策略就直接给出最终总结"),
        turns=(
            ConversationTurn(
                user_input="setup 完成后，模板先别默认落定，先问我要不要自定义。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("询问是否需要自定义模板",),
                assert_safety=("暂停等待模板输入",),
                forbidden_behavior=("直接输出最终总结",),
            ),
            ConversationTurn(
                user_input="请用下面这份完整 Markdown 模板整体替换当前模板：# 技术方案\n\n## 背景\n\n## 目标\n\n## 方案设计\n\n## 风险与验证",
                expected_result="SUCCESS_REPLACE_TEMPLATE",
                assert_paths=(".architecture/templates/technical-solution-template.md",),
                assert_structure=("整体替换单个目标文件",),
                assert_safety=("不做局部 merge",),
                forbidden_behavior=("局部编辑", "内容合并"),
            ),
        ),
    ),
)


CREATE_TECHNICAL_SOLUTION_CASES = (
    vcase(
        "CTS-01",
        "create-technical-solution",
        "流程场景层",
        "empty-project",
        "在没有 `.architecture/` 前置的空仓库中直接请求创建技术方案。",
        "前置全缺失时立即停止并回指 setup-architect",
        "STOP_AND_REDIRECT",
        assert_paths=(
            ".architecture/members.yml",
            ".architecture/principles.md",
            ".architecture/templates/technical-solution-template.md",
        ),
        assert_semantics=("响应明确列出全部缺失前置并回指 setup-architect",),
        assert_safety=("不自动创建 .architecture/*", "不继续生成技术方案"),
        forbidden_behavior=("伪造初始化产物",),
    ),
    vcase(
        "CTS-02",
        "create-technical-solution",
        "流程场景层",
        "partial-architecture-missing-one-file",
        "在只缺少一个关键前置文件的仓库中请求创建技术方案。",
        "任一关键前置缺失都必须停机",
        "STOP_AND_REDIRECT",
        assert_paths=(
            ".architecture/members.yml",
            ".architecture/principles.md",
            ".architecture/templates/technical-solution-template.md",
        ),
        assert_safety=("不允许半继续执行",),
        forbidden_behavior=("跳过缺失项继续生成",),
    ),
    vcase(
        "CTS-03",
        "create-technical-solution",
        "行为回归层",
        "complete-architecture-default-template",
        "在默认模板和前置完整的仓库中，为“payment pipeline rework”创建技术方案。",
        "标准成功路径把结果写到正式目录",
        "SUCCESS_CREATE",
        assert_paths=(".architecture/technical-solutions/payment-pipeline-rework.md",),
        assert_structure=("生成正式技术方案文档",),
        assert_safety=("不写入其他目录",),
        forbidden_behavior=("输出聊天式说明替代文档",),
    ),
    vcase(
        "CTS-04",
        "create-technical-solution",
        "行为回归层",
        "complete-architecture-custom-template",
        "在自定义模板已安装的仓库中，为同一主题创建技术方案。",
        "结果必须遵循当前自定义模板，而不是默认模板",
        "SUCCESS_CREATE",
        assert_structure=("保留当前模板顶层结构",),
        assert_semantics=("先读取当前模板",),
        assert_safety=("不回退默认模板结构",),
        forbidden_behavior=("发明默认顶层章节",),
    ),
    vcase(
        "CTS-05",
        "create-technical-solution",
        "行为回归层",
        "complete-architecture-custom-template",
        "在自定义模板场景下生成技术方案，并包含需要展开的小节和表格内容。",
        "允许加小节但禁止新增模板外一级章节",
        "SUCCESS_CREATE",
        assert_structure=("一级结构保持不变",),
        assert_safety=("只在现有章节内细化",),
        forbidden_behavior=("新增用户模板没有定义的一级章节",),
    ),
    vcase(
        "CTS-06",
        "create-technical-solution",
        "行为回归层",
        "complete-architecture-default-template",
        "在默认模板场景下生成正式技术方案，并提供足够上下文覆盖所有必填信息块。",
        "所有必填信息块都必须被覆盖",
        "SUCCESS_CREATE",
        assert_semantics=(
            "问题与背景",
            "目标与非目标",
            "约束与依赖",
            "推荐方案",
            "备选方案与权衡",
            "详细设计",
            "风险与缓解",
            "实施建议",
            "评审关注点",
            "未决问题",
        ),
        assert_safety=("不遗漏强制信息块",),
        forbidden_behavior=("只输出零散结论",),
    ),
    vcase(
        "CTS-07",
        "create-technical-solution",
        "对抗边界层",
        "complete-architecture-custom-template",
        "在结构明显不足的自定义模板下请求生成技术方案。",
        "模板无法安全承载信息块时必须停下来询问",
        "STOP_AND_ASK",
        assert_semantics=("明确说明无法安全落位的信息块",),
        assert_safety=("不擅自新增一级章节",),
        forbidden_behavior=("猜测模板语义继续生成",),
    ),
    vcase(
        "CTS-08",
        "create-technical-solution",
        "对抗边界层",
        "existing-solution-file",
        "当 `.architecture/technical-solutions/payment-pipeline-rework.md` 已存在时再次请求生成同主题方案。",
        "目标文件已存在时必须先确认覆盖或另存",
        "STOP_AND_ASK",
        assert_paths=(".architecture/technical-solutions/payment-pipeline-rework.md",),
        assert_safety=("没有未经确认覆盖已有文件",),
        forbidden_behavior=("静默覆盖既有文档",),
    ),
    vcase(
        "CTS-09",
        "create-technical-solution",
        "行为回归层",
        "existing-solution-file",
        "已有同名目标文件时，用户明确拒绝覆盖并要求保留现有文档。",
        "用户拒绝覆盖时保留原文件并等待另存决策",
        "SUCCESS_SAVE_AS",
        assert_paths=(".architecture/technical-solutions/payment-pipeline-rework.md",),
        assert_safety=("原文件内容保持不变，且停止覆盖原文件",),
        forbidden_behavior=("继续写回原路径",),
    ),
    vcase(
        "CTS-10",
        "create-technical-solution",
        "对抗边界层",
        "complete-architecture-default-template",
        "主题同时命中多个 solution type 时请求生成技术方案。",
        "多类型主题按成员并集参与，且始终包含系统架构师",
        "SUCCESS_CREATE",
        assert_semantics=("成员取并集并去重", "系统架构师始终参与"),
        assert_safety=("不遗漏高风险主题所需成员",),
        forbidden_behavior=("只按单一类型裁剪成员",),
    ),
    vcase(
        "CTS-11",
        "create-technical-solution",
        "流程场景层",
        "complete-architecture-default-template",
        "在未刚执行 setup-architect 的独立会话中，基于已存在前置直接请求创建技术方案。",
        "前置齐全时应能独立执行，不依赖刚跑过 setup",
        "SUCCESS_CREATE",
        assert_paths=(".architecture/technical-solutions/payment-pipeline-rework.md",),
        assert_semantics=("仅依赖既有 .architecture 契约",),
        assert_safety=("不要求 setup 继续参与",),
        forbidden_behavior=("回头猜安装过程上下文",),
    ),
    vcase(
        "CTS-12",
        "create-technical-solution",
        "对抗边界层",
        "partial-architecture-missing-one-file",
        "关键前置不完整时，诱导 skill 一边补环境一边生成技术方案。",
        "前置不完整时不得脑补成员、原则或模板",
        "STOP_AND_REDIRECT",
        assert_safety=("不边补环境边写 solution",),
        forbidden_behavior=("伪造 members.yml", "伪造 principles.md", "伪造模板文件"),
    ),
    vcase(
        "CTS-13",
        "create-technical-solution",
        "对抗边界层",
        "complete-architecture-default-template",
        "第六步已收集上下文，但专家分析和协作收敛没有显式引用任何共享上下文编号，仍试图继续成稿。",
        "缺少共享上下文消费链时必须停机并回退到受影响阶段",
        "STOP_AND_ASK",
        assert_semantics=("明确指出缺失的共享上下文消费链",),
        assert_safety=("不允许无证据继续成稿",),
        forbidden_behavior=("跳过上下文引用继续生成最终方案",),
    ),
)


REVIEW_TECHNICAL_SOLUTION_CASES = (
    vcase(
        "RTS-01",
        "review-technical-solution",
        "流程场景层",
        "review-solution-missing-principles",
        "在缺少 `.architecture/principles.md` 的仓库中请求对完整技术方案开展正式评审。",
        "缺失评审前置时必须停止正式评审",
        "STOP_FORMAL_REVIEW",
        assert_paths=(".architecture/principles.md",),
        assert_semantics=("结论为 '无法开展正式评审'",),
        assert_safety=("不输出通过/需修改",),
        forbidden_behavior=("通过", "需修改"),
    ),
    vcase(
        "RTS-02",
        "review-technical-solution",
        "流程场景层",
        "review-solution-no-code-context",
        "用户只提供方案文档，不提供相关代码或核心模块路径，就要求完成正式技术评审。",
        "没有相关代码时必须先索要核心模块路径或代码范围",
        "STOP_FORMAL_REVIEW",
        assert_semantics=("明确要求提供核心模块路径或代码范围",),
        assert_safety=("不在缺少代码上下文时给出正式通过结论",),
    ),
    vcase(
        "RTS-03",
        "review-technical-solution",
        "对抗边界层",
        "review-solution-summary-only",
        "用户仅给出方案摘要而未提供完整方案正文，却要求进行正式技术评审。",
        "只有摘要没有完整方案正文时必须停机",
        "STOP_FORMAL_REVIEW",
        assert_safety=("不基于摘要脑补正式评审",),
    ),
    vcase(
        "RTS-04",
        "review-technical-solution",
        "行为回归层",
        "review-solution-complete-inputs",
        "提供完整方案、原则、相关代码与上下文，对方案执行正式技术评审。",
        "完整输入下输出必须保持固定报告结构",
        "SUCCESS_REVIEW",
        assert_structure=(
            "保留全部六个固定报告章节",
            "空章节显式写为 - 无",
        ),
        assert_semantics=(
            "评审结论",
            "阻断项",
            "主要问题",
            "改进方案",
            "待补充信息",
            "建议验证",
        ),
    ),
    vcase(
        "RTS-05",
        "review-technical-solution",
        "行为回归层",
        "review-solution-cross-system-security",
        "评审一个跨系统且带安全影响的多类别技术方案。",
        "多类别高风险方案应明确主分类、附加分类并优先呈现高风险问题",
        "SUCCESS_REVIEW",
        assert_semantics=("主分类", "附加分类", "高风险问题优先排序"),
        assert_safety=("不把高风险问题埋在低优先级之后",),
    ),
    vcase(
        "RTS-06",
        "review-technical-solution",
        "行为回归层",
        "review-solution-claimed-event-bus-reuse",
        "方案声称复用现有订单事件总线实现，要求核验代码与方案一致性。",
        "找不到声称复用实现时必须输出阻断级问题",
        "SUCCESS_REVIEW",
        assert_semantics=("代码中未找到对应实现", "`severity`: `blocker`"),
        assert_safety=("不能把缺失关键实现降级处理",),
    ),
    vcase(
        "RTS-07",
        "review-technical-solution",
        "对抗边界层",
        "review-solution-request-skip-code-review",
        "用户要求跳过代码核验，只基于文档快速给出正式评审结论。",
        "用户要求降标时必须拒绝并维持正式评审标准",
        "STOP_FORMAL_REVIEW",
        assert_safety=("明确拒绝降低评审标准",),
    ),
    vcase(
        "RTS-08",
        "review-technical-solution",
        "对抗边界层",
        "review-solution-partial-core-code",
        "用户仅提供部分核心路径代码，却要求输出正式评审通过与完整结论。",
        "核心代码覆盖不全时必须停机而不是给出成功评审",
        "STOP_FORMAL_REVIEW",
        assert_semantics=("结论为 '无法开展正式评审'", "未核验范围", "待核验风险"),
        assert_safety=("不把部分核验伪装成成功评审",),
    ),
    vcase(
        "RTS-09",
        "review-technical-solution",
        "静态契约层",
        "review-solution-complete-inputs",
        "在没有阻断问题的完整评审路径中，检查正式输出契约是否始终保留完整结构。",
        "即使没有 blocker 也必须保留六段式输出并显式标记空章节",
        "SUCCESS_REVIEW",
        assert_structure=("保留全部六个固定报告章节",),
        assert_semantics=("空章节使用 - 无",),
        assert_safety=("不因内容为空而删除章节",),
    ),
)


ALL_CASES = SETUP_ARCHITECT_CASES + CREATE_TECHNICAL_SOLUTION_CASES + REVIEW_TECHNICAL_SOLUTION_CASES

PHASE_1_CASE_IDS = (
    "SA-01",
    "SA-02",
    "SA-13",
    "SA-07",
    "SA-08",
    "CTS-01",
    "CTS-02",
    "CTS-04",
    "CTS-07",
    "CTS-08",
    "RTS-01",
    "RTS-02",
    "RTS-03",
)

PHASE_2_CASE_IDS = (
    "SA-03",
    "SA-04",
    "SA-05",
    "SA-06",
    "SA-14",
    "CTS-03",
    "CTS-05",
    "CTS-06",
    "CTS-09",
    "RTS-04",
    "RTS-05",
    "RTS-06",
)

PHASE_3_CASE_IDS = (
    "SA-09",
    "SA-10",
    "SA-11",
    "SA-12",
    "CTS-10",
    "CTS-11",
    "CTS-12",
    "CTS-13",
    "RTS-07",
    "RTS-08",
    "RTS-09",
)

CASE_INDEX = {case.case_id: case for case in ALL_CASES}
