from dataclasses import dataclass
from typing import Tuple


@dataclass(frozen=True)
class SetupProgress:
    members_customized: bool = False
    principles_customized: bool = False
    structure_verified: bool = False


@dataclass(frozen=True)
class ReviewProgress:
    inputs_ready: bool = False
    type_classified: bool = False
    claims_extracted: bool = False
    evidence_assigned: bool = False
    issues_classified: bool = False
    recommendations_defined: bool = False
    self_check_passed: bool = False


@dataclass(frozen=True)
class CreateProgress:
    scope_clarified: bool = False
    prerequisites_ready: bool = False
    template_read: bool = False
    solution_typed: bool = False
    participants_selected: bool = False
    context_built: bool = False
    task_sheet_ready: bool = False
    expert_analysis_complete: bool = False
    synthesis_complete: bool = False
    draft_written: bool = False
    absorb_check_passed: bool = False


@dataclass(frozen=True)
class ConversationTurn:
    user_input: str
    expected_result: str
    assert_paths: Tuple[str, ...] = ()
    assert_structure: Tuple[str, ...] = ()
    assert_semantics: Tuple[str, ...] = ()
    assert_safety: Tuple[str, ...] = ()
    forbidden_behavior: Tuple[str, ...] = ()
    setup_progress: SetupProgress | None = None
    required_setup_step: int | None = None
    setup_turn_action: str | None = None
    blocked_steps: Tuple[int, ...] = ()
    review_progress: ReviewProgress | None = None
    required_review_step: int | None = None
    review_turn_action: str | None = None
    create_progress: CreateProgress | None = None
    required_create_step: int | None = None
    create_turn_action: str | None = None


@dataclass(frozen=True)
class ValidationCase:
    case_id: str
    skill: str
    layer: str
    fixture: str
    prompt: str
    purpose: str
    expected_result: str
    assert_paths: Tuple[str, ...] = ()
    assert_structure: Tuple[str, ...] = ()
    assert_semantics: Tuple[str, ...] = ()
    assert_safety: Tuple[str, ...] = ()
    forbidden_behavior: Tuple[str, ...] = ()
    turns: Tuple[ConversationTurn, ...] = ()


def vcase(
    case_id: str,
    skill: str,
    layer: str,
    fixture: str,
    prompt: str,
    purpose: str,
    expected_result: str,
    *,
    assert_paths: Tuple[str, ...] = (),
    assert_structure: Tuple[str, ...] = (),
    assert_semantics: Tuple[str, ...] = (),
    assert_safety: Tuple[str, ...] = (),
    forbidden_behavior: Tuple[str, ...] = (),
    turns: Tuple[ConversationTurn, ...] = (),
) -> ValidationCase:
    return ValidationCase(
        case_id=case_id,
        skill=skill,
        layer=layer,
        fixture=fixture,
        prompt=prompt,
        purpose=purpose,
        expected_result=expected_result,
        assert_paths=assert_paths,
        assert_structure=assert_structure,
        assert_semantics=assert_semantics,
        assert_safety=assert_safety,
        forbidden_behavior=forbidden_behavior,
        turns=turns,
    )


SETUP_ARCHITECT_CASES = (
    vcase(
        "SA-01",
        "setup-architect",
        "流程场景层",
        "empty-project",
        "在空仓库中请求执行 setup-architect 初始化默认架构框架。",
        "锁定最基础的 setup 成功路径",
        "SUCCESS_INIT",
        assert_paths=(
            ".architecture/technical-solutions/",
            ".architecture/templates/",
            ".architecture/templates/technical-solution-template.md",
            ".architecture/members.yml",
            ".architecture/principles.md",
        ),
        assert_structure=(".architecture 最小结构完整",),
        assert_safety=("只创建最小必需结构",),
        forbidden_behavior=("写入 legacy 路径",),
    ),
    vcase(
        "SA-02",
        "setup-architect",
        "流程场景层",
        "complete-architecture-default-template",
        "在已完成初始化的仓库中再次请求执行 setup-architect 完整安装流程。",
        "防止重复 setup 产生重复目录和副产物",
        "SUCCESS_INIT",
        assert_paths=(".architecture/",),
        assert_structure=("不生成 .architecture/.architecture", "不生成重复模板"),
        assert_safety=("不引入 legacy 或临时副产物",),
        forbidden_behavior=("嵌套 .architecture", "重复模板副本"),
    ),
    vcase(
        "SA-03",
        "setup-architect",
        "行为回归层",
        "partial-architecture-missing-one-file",
        "在只缺少一个必需文件的已部分初始化仓库中请求补齐 setup。",
        "只补缺失项，不覆盖已有项",
        "SUCCESS_INIT",
        assert_paths=(
            ".architecture/members.yml",
            ".architecture/principles.md",
            ".architecture/templates/technical-solution-template.md",
        ),
        assert_structure=("现有文件保持原位",),
        assert_safety=("仅补齐缺失的单个前置文件，已有内容不被无提示覆盖",),
        forbidden_behavior=("重写无缺失文件",),
    ),
    vcase(
        "SA-04",
        "setup-architect",
        "行为回归层",
        "complete-architecture-default-template",
        "初始化流程询问模板定制时，用户明确回答保留当前模板。",
        "用户拒绝定制模板时保留当前模板",
        "SUCCESS_INIT",
        assert_paths=(".architecture/templates/technical-solution-template.md",),
        assert_structure=("模板路径不变",),
        assert_semantics=("模板最终状态明确为保留当前模板",),
        assert_safety=("不发生模板替换",),
        forbidden_behavior=("无用户请求时覆盖模板",),
    ),
    vcase(
        "SA-05",
        "setup-architect",
        "行为回归层",
        "template-replacement-inputs",
        "完整初始化结束后，用户提供完整 Markdown 模板并要求替换当前模板。",
        "初始化尾声允许整文件替换模板",
        "SUCCESS_REPLACE_TEMPLATE",
        assert_paths=(".architecture/templates/technical-solution-template.md",),
        assert_structure=("整体替换单个目标文件",),
        assert_safety=("不做局部 merge",),
        forbidden_behavior=("局部编辑", "内容合并"),
    ),
    vcase(
        "SA-06",
        "setup-architect",
        "行为回归层",
        "complete-architecture-default-template",
        "安装完成后单独请求替换 `.architecture/templates/technical-solution-template.md`。",
        "安装后仅替换模板时跳过完整 setup",
        "SUCCESS_REPLACE_TEMPLATE",
        assert_paths=(".architecture/templates/technical-solution-template.md",),
        assert_structure=("只走模板替换分支",),
        assert_safety=("不重跑初始化流程",),
        forbidden_behavior=("重新安装 .architecture 基础结构",),
    ),
    vcase(
        "SA-07",
        "setup-architect",
        "对抗边界层",
        "partial-architecture-missing-one-file",
        "在缺少模板目录、模板文件、成员文件或原则文件之一时，请求只执行模板替换分支。",
        "模板替换前置不满足时必须停机",
        "STOP_AND_REDIRECT",
        assert_paths=(
            ".architecture/templates/",
            ".architecture/templates/technical-solution-template.md",
            ".architecture/members.yml",
            ".architecture/principles.md",
        ),
        assert_semantics=("响应明确点名缺失的前置路径",),
        assert_safety=("要求先完成完整 setup", "不静默补文件"),
        forbidden_behavior=("边补环境边替换模板",),
    ),
    vcase(
        "SA-08",
        "setup-architect",
        "对抗边界层",
        "template-replacement-inputs",
        "用户仅提供模板片段、patch 或口头描述并要求替换技术方案模板。",
        "拒绝模板片段和口头描述输入",
        "STOP_AND_ASK",
        assert_semantics=("继续索要完整 Markdown、路径或链接",),
        assert_safety=("不自动生成模板", "不做局部编辑", "不做内容合并"),
        forbidden_behavior=("根据片段脑补完整模板",),
    ),
    vcase(
        "SA-09",
        "setup-architect",
        "行为回归层",
        "complete-architecture-default-template",
        "用户请求自定义成员配置，并尝试加入新的专家角色。",
        "成员定制必须保留核心成员",
        "SUCCESS_INIT",
        assert_semantics=(
            "保留系统架构师",
            "保留领域专家",
            "保留安全专家",
            "保留性能专家",
            "保留可维护性专家",
        ),
        assert_safety=("允许增补专家，不允许替换核心成员",),
        forbidden_behavior=("删除核心成员",),
    ),
    vcase(
        "SA-10",
        "setup-architect",
        "行为回归层",
        "complete-architecture-default-template",
        "用户请求自定义架构原则，并希望调整团队的评审与决策准则。",
        "原则定制必须保留核心原则和最低覆盖范围",
        "SUCCESS_INIT",
        assert_semantics=(
            "保留核心原则",
            "覆盖模块边界与依赖方向",
            "覆盖 API / 事件 / 数据边界",
            "覆盖测试和验证基线",
            "覆盖安全与合规底线",
            "覆盖技术方案和实施计划的决策标准",
        ),
        assert_safety=("不删除核心原则",),
        forbidden_behavior=("删除核心原则",),
    ),
    vcase(
        "SA-11",
        "setup-architect",
        "静态契约层",
        "complete-architecture-default-template",
        "setup-architect 完成初始化并准备输出最终总结。",
        "最终总结前结构必须已验证",
        "SUCCESS_INIT",
        assert_paths=(
            ".architecture/technical-solutions/",
            ".architecture/templates/",
            ".architecture/templates/technical-solution-template.md",
            ".architecture/members.yml",
            ".architecture/principles.md",
        ),
        assert_safety=("无 legacy 目录",),
        forbidden_behavior=(
            "保留 .architecture/solutions",
            ".architecture/plans",
            ".architecture/reviews",
        ),
    ),
    vcase(
        "SA-12",
        "setup-architect",
        "静态契约层",
        "empty-project",
        "在空仓库中执行 setup-architect，检查初始化过程是否引入无关文件或目录。",
        "安装和初始化不应引入无关产物",
        "SUCCESS_INIT",
        assert_structure=("assistant 目标目录唯一",),
        assert_safety=("无 CLAUDE.md", "无 agent_docs", "无嵌套 .git", "无随机 temp 目录"),
        forbidden_behavior=("生成无关安装副产物",),
    ),
    vcase(
        "SA-13",
        "setup-architect",
        "流程场景层",
        "complete-architecture-default-template",
        "setup-architect 初始化后进入模板定制确认对话。",
        "验证多轮确认后可保留当前模板",
        "SUCCESS_INIT",
        assert_semantics=("先确认是否需要定制模板",),
        assert_safety=("未确认前不直接输出最终总结",),
        forbidden_behavior=("未确认模板策略就直接给出最终总结",),
        turns=(
            ConversationTurn(
                user_input="先完成 setup-architect 初始化，模板部分你先别直接定，先问我要不要自定义。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("询问是否需要自定义模板",),
                assert_safety=("暂停等待模板决策",),
                forbidden_behavior=("直接输出最终总结",),
                setup_progress=SetupProgress(
                    members_customized=True,
                    principles_customized=True,
                    structure_verified=True,
                ),
                required_setup_step=6,
                setup_turn_action="await_template_decision",
            ),
            ConversationTurn(
                user_input="不用自定义，保持当前模板即可。",
                expected_result="SUCCESS_INIT",
                assert_paths=(".architecture/templates/technical-solution-template.md",),
                assert_semantics=("模板最终状态明确为保留当前模板",),
                assert_safety=("不发生模板替换",),
                forbidden_behavior=("无用户请求时覆盖模板",),
                setup_progress=SetupProgress(
                    members_customized=True,
                    principles_customized=True,
                    structure_verified=True,
                ),
                required_setup_step=6,
                setup_turn_action="keep_current_template",
            ),
        ),
    ),
    vcase(
        "SA-14",
        "setup-architect",
        "行为回归层",
        "template-replacement-inputs",
        "setup-architect 初始化后进入模板替换确认对话。",
        "验证多轮确认后可整体替换模板",
        "SUCCESS_REPLACE_TEMPLATE",
        assert_paths=(".architecture/templates/technical-solution-template.md",),
        assert_structure=("整体替换单个目标文件",),
        assert_safety=("不做局部 merge", "未确认前不直接输出最终总结"),
        forbidden_behavior=("局部编辑", "内容合并", "未确认模板策略就直接给出最终总结"),
        turns=(
            ConversationTurn(
                user_input="setup 完成后，模板先别默认落定，先问我要不要自定义。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("询问是否需要自定义模板",),
                assert_safety=("暂停等待模板输入",),
                forbidden_behavior=("直接输出最终总结",),
                setup_progress=SetupProgress(
                    members_customized=True,
                    principles_customized=True,
                    structure_verified=True,
                ),
                required_setup_step=6,
                setup_turn_action="await_template_decision",
            ),
            ConversationTurn(
                user_input="请用下面这份完整 Markdown 模板整体替换当前模板：# 技术方案\n\n## 背景\n\n## 目标\n\n## 方案设计\n\n## 风险与验证",
                expected_result="SUCCESS_REPLACE_TEMPLATE",
                assert_paths=(".architecture/templates/technical-solution-template.md",),
                assert_structure=("整体替换单个目标文件",),
                assert_safety=("不做局部 merge",),
                forbidden_behavior=("局部编辑", "内容合并"),
                setup_progress=SetupProgress(
                    members_customized=True,
                    principles_customized=True,
                    structure_verified=True,
                ),
                required_setup_step=6,
                setup_turn_action="replace_template",
            ),
        ),
    ),
    vcase(
        "SA-15",
        "setup-architect",
        "流程场景层",
        "empty-project",
        "setup-architect 在成员定制所需上下文不足时，必须停在第 3 步。",
        "验证未完成第 3 步时不会进入第 4 到 6 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在成员定制",),
        assert_safety=("未完成第 3 步不得进入第 4 步",),
        forbidden_behavior=("进入第 4 步", "进入第 5 步", "进入第 6 步"),
        turns=(
            ConversationTurn(
                user_input="当前仓库上下文几乎没有可用于成员定制的信息。你不能跳到下一步，先处理 setup。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("成员定制", "要求补充成员所需项目上下文"),
                assert_safety=("未完成第 3 步，不得进入第 4 步。",),
                forbidden_behavior=("进入第 4 步", "原则定制", "模板确认"),
                setup_progress=SetupProgress(),
                required_setup_step=3,
                setup_turn_action="await_context",
                blocked_steps=(4, 5, 6),
            ),
            ConversationTurn(
                user_input="模板的事情先不要问，也不要做原则定制；当前成员信息还是不够。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("成员定制", "项目上下文不足"),
                assert_safety=("未完成第 3 步，不得进入第 4 步。",),
                forbidden_behavior=("进入第 4 步", "进入第 5 步", "进入第 6 步"),
                setup_progress=SetupProgress(),
                required_setup_step=3,
                setup_turn_action="await_context",
                blocked_steps=(4, 5, 6),
            ),
        ),
    ),
    vcase(
        "SA-16",
        "setup-architect",
        "流程场景层",
        "complete-architecture-default-template",
        "成员定制完成但原则定制上下文不足时，setup-architect 必须停在第 4 步。",
        "验证未完成第 4 步时不会进入第 5 到 6 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在原则定制",),
        assert_safety=("未完成第 4 步不得进入第 5 步",),
        forbidden_behavior=("进入第 5 步", "进入第 6 步"),
        turns=(
            ConversationTurn(
                user_input="成员先按现状保留，但原则文档需要的项目判断基线还不够。不要继续往后。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("原则定制", "要求补充原则定制所需项目上下文"),
                assert_safety=("未完成第 4 步，不得进入第 5 步。",),
                forbidden_behavior=("进入第 5 步", "结构复核", "模板确认"),
                setup_progress=SetupProgress(members_customized=True),
                required_setup_step=4,
                setup_turn_action="await_context",
                blocked_steps=(5, 6),
            ),
            ConversationTurn(
                user_input="还是先别做结构复核，原则这一步的信息依然不够。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("原则定制", "项目上下文不足"),
                assert_safety=("未完成第 4 步，不得进入第 5 步。",),
                forbidden_behavior=("进入第 5 步", "进入第 6 步"),
                setup_progress=SetupProgress(members_customized=True),
                required_setup_step=4,
                setup_turn_action="await_context",
                blocked_steps=(5, 6),
            ),
        ),
    ),
    vcase(
        "SA-17",
        "setup-architect",
        "流程场景层",
        "complete-architecture-default-template",
        "成员和原则都已完成，但正式结构尚未复核时，setup-architect 必须停在第 5 步。",
        "验证未完成第 5 步时不会进入第 6 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在结构复核",),
        assert_safety=("未完成第 5 步不得进入第 6 步",),
        forbidden_behavior=("进入第 6 步",),
        turns=(
            ConversationTurn(
                user_input="成员和原则先按当前结果保留，但正式结构还没复核完，现在不能问模板。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("结构复核", "结构验证"),
                assert_safety=("未完成第 5 步，不得进入第 6 步。",),
                forbidden_behavior=("进入第 6 步", "模板确认"),
                setup_progress=SetupProgress(members_customized=True, principles_customized=True),
                required_setup_step=5,
                setup_turn_action="await_context",
                blocked_steps=(6,),
            ),
            ConversationTurn(
                user_input="先别问模板，结构复核这一步还是没完成。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("结构复核", "结构验证"),
                assert_safety=("未完成第 5 步，不得进入第 6 步。",),
                forbidden_behavior=("进入第 6 步",),
                setup_progress=SetupProgress(members_customized=True, principles_customized=True),
                required_setup_step=5,
                setup_turn_action="await_context",
                blocked_steps=(6,),
            ),
        ),
    ),
)


CREATE_TECHNICAL_SOLUTION_CASES = (
    vcase(
        "CTS-01",
        "create-technical-solution",
        "流程场景层",
        "empty-project",
        "在没有 `.architecture/` 前置的空仓库中直接请求创建技术方案。",
        "前置全缺失时立即停止并回指 setup-architect",
        "STOP_AND_REDIRECT",
        assert_paths=(
            ".architecture/members.yml",
            ".architecture/principles.md",
            ".architecture/templates/technical-solution-template.md",
        ),
        assert_semantics=("响应明确列出全部缺失前置并回指 setup-architect",),
        assert_safety=("不自动创建 .architecture/*", "不继续生成技术方案"),
        forbidden_behavior=("伪造初始化产物",),
    ),
    vcase(
        "CTS-02",
        "create-technical-solution",
        "流程场景层",
        "partial-architecture-missing-one-file",
        "在只缺少一个关键前置文件的仓库中请求创建技术方案。",
        "任一关键前置缺失都必须停机",
        "STOP_AND_REDIRECT",
        assert_paths=(
            ".architecture/members.yml",
            ".architecture/principles.md",
            ".architecture/templates/technical-solution-template.md",
        ),
        assert_safety=("不允许半继续执行",),
        forbidden_behavior=("跳过缺失项继续生成",),
    ),
    vcase(
        "CTS-03",
        "create-technical-solution",
        "行为回归层",
        "complete-architecture-default-template",
        "在默认模板和前置完整的仓库中，为“payment pipeline rework”创建技术方案。",
        "标准成功路径把结果写到正式目录",
        "SUCCESS_CREATE",
        assert_paths=(".architecture/technical-solutions/payment-pipeline-rework.md",),
        assert_structure=("生成正式技术方案文档",),
        assert_safety=("不写入其他目录",),
        forbidden_behavior=("输出聊天式说明替代文档",),
    ),
    vcase(
        "CTS-04",
        "create-technical-solution",
        "行为回归层",
        "complete-architecture-custom-template",
        "在自定义模板已安装的仓库中，为同一主题创建技术方案。",
        "结果必须遵循当前自定义模板，而不是默认模板",
        "SUCCESS_CREATE",
        assert_structure=("保留当前模板顶层结构",),
        assert_semantics=("先读取当前模板",),
        assert_safety=("不回退默认模板结构",),
        forbidden_behavior=("发明默认顶层章节",),
    ),
    vcase(
        "CTS-05",
        "create-technical-solution",
        "行为回归层",
        "complete-architecture-custom-template",
        "在自定义模板场景下生成技术方案，并包含需要展开的小节和表格内容。",
        "允许加小节但禁止新增模板外一级章节",
        "SUCCESS_CREATE",
        assert_structure=("一级结构保持不变",),
        assert_safety=("只在现有章节内细化",),
        forbidden_behavior=("新增用户模板没有定义的一级章节",),
    ),
    vcase(
        "CTS-06",
        "create-technical-solution",
        "行为回归层",
        "complete-architecture-default-template",
        "在默认模板场景下生成正式技术方案，并提供足够上下文覆盖所有必填信息块。",
        "所有必填信息块都必须被覆盖",
        "SUCCESS_CREATE",
        assert_semantics=(
            "问题与背景",
            "目标与非目标",
            "约束与依赖",
            "推荐方案",
            "备选方案与权衡",
            "详细设计",
            "风险与缓解",
            "实施建议",
            "评审关注点",
            "未决问题",
        ),
        assert_safety=("不遗漏强制信息块",),
        forbidden_behavior=("只输出零散结论",),
    ),
    vcase(
        "CTS-07",
        "create-technical-solution",
        "对抗边界层",
        "complete-architecture-custom-template",
        "在结构明显不足的自定义模板下请求生成技术方案。",
        "模板无法安全承载信息块时必须停下来询问",
        "STOP_AND_ASK",
        assert_semantics=("明确说明无法安全落位的信息块",),
        assert_safety=("不擅自新增一级章节",),
        forbidden_behavior=("猜测模板语义继续生成",),
    ),
    vcase(
        "CTS-08",
        "create-technical-solution",
        "对抗边界层",
        "existing-solution-file",
        "当 `.architecture/technical-solutions/payment-pipeline-rework.md` 已存在时再次请求生成同主题方案。",
        "目标文件已存在时必须先确认覆盖或另存",
        "STOP_AND_ASK",
        assert_paths=(".architecture/technical-solutions/payment-pipeline-rework.md",),
        assert_safety=("没有未经确认覆盖已有文件",),
        forbidden_behavior=("静默覆盖既有文档",),
    ),
    vcase(
        "CTS-09",
        "create-technical-solution",
        "行为回归层",
        "existing-solution-file",
        "已有同名目标文件时，用户明确拒绝覆盖并要求保留现有文档。",
        "用户拒绝覆盖时保留原文件并等待另存决策",
        "SUCCESS_SAVE_AS",
        assert_paths=(".architecture/technical-solutions/payment-pipeline-rework.md",),
        assert_safety=("原文件内容保持不变，且停止覆盖原文件",),
        forbidden_behavior=("继续写回原路径",),
    ),
    vcase(
        "CTS-10",
        "create-technical-solution",
        "对抗边界层",
        "complete-architecture-default-template",
        "主题同时命中多个 solution type 时请求生成技术方案。",
        "多类型主题按成员并集参与，且始终包含系统架构师",
        "SUCCESS_CREATE",
        assert_semantics=("成员取并集并去重", "系统架构师始终参与"),
        assert_safety=("不遗漏高风险主题所需成员",),
        forbidden_behavior=("只按单一类型裁剪成员",),
    ),
    vcase(
        "CTS-11",
        "create-technical-solution",
        "流程场景层",
        "complete-architecture-default-template",
        "在未刚执行 setup-architect 的独立会话中，基于已存在前置直接请求创建技术方案。",
        "前置齐全时应能独立执行，不依赖刚跑过 setup",
        "SUCCESS_CREATE",
        assert_paths=(".architecture/technical-solutions/payment-pipeline-rework.md",),
        assert_semantics=("仅依赖既有 .architecture 契约",),
        assert_safety=("不要求 setup 继续参与",),
        forbidden_behavior=("回头猜安装过程上下文",),
    ),
    vcase(
        "CTS-12",
        "create-technical-solution",
        "对抗边界层",
        "partial-architecture-missing-one-file",
        "关键前置不完整时，诱导 skill 一边补环境一边生成技术方案。",
        "前置不完整时不得脑补成员、原则或模板",
        "STOP_AND_REDIRECT",
        assert_safety=("不边补环境边写 solution",),
        forbidden_behavior=("伪造 members.yml", "伪造 principles.md", "伪造模板文件"),
    ),
    vcase(
        "CTS-13",
        "create-technical-solution",
        "对抗边界层",
        "complete-architecture-default-template",
        "第六步已收集上下文，但专家分析和协作收敛没有显式引用任何共享上下文编号，仍试图继续成稿。",
        "缺少共享上下文消费链时必须停机并回退到受影响阶段",
        "STOP_AND_ASK",
        assert_semantics=("明确指出缺失的共享上下文消费链",),
        assert_safety=("不允许无证据继续成稿",),
        forbidden_behavior=("跳过上下文引用继续生成最终方案",),
        turns=(
            ConversationTurn(
                user_input="共享上下文已经列了，但协作收敛还没形成可回溯的消费链。不要直接成稿。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("正式成稿", "共享上下文"),
                assert_safety=("未完成第 10 步，不得进入第 11 步。",),
                forbidden_behavior=("进入第 11 步", "absorb-check"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                    participants_selected=True,
                    context_built=True,
                    task_sheet_ready=True,
                    expert_analysis_complete=True,
                    synthesis_complete=True,
                ),
                required_create_step=10,
                create_turn_action="await_context",
                blocked_steps=(11, 12),
            ),
            ConversationTurn(
                user_input="先别做 absorb-check，正式成稿这一步还没闭合。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("正式成稿", "共享上下文"),
                assert_safety=("未完成第 10 步，不得进入第 11 步。",),
                forbidden_behavior=("进入第 11 步", "进入第 12 步"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                    participants_selected=True,
                    context_built=True,
                    task_sheet_ready=True,
                    expert_analysis_complete=True,
                    synthesis_complete=True,
                ),
                required_create_step=10,
                create_turn_action="await_context",
                blocked_steps=(11, 12),
            ),
        ),
    ),
    vcase(
        "CTS-14",
        "create-technical-solution",
        "流程场景层",
        "complete-architecture-default-template",
        "主题和范围仍模糊时，create-technical-solution 必须停在第 1 步。",
        "验证未完成第 1 步时不会进入第 2 到 12 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在定题与范围判断",),
        assert_safety=("未完成第 1 步不得进入第 2 步",),
        forbidden_behavior=("进入第 2 步", "进入第 5 步", "进入第 10 步"),
        turns=(
            ConversationTurn(
                user_input="主题还很模糊，先别去检查模板和成员。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("定题", "范围"),
                assert_safety=("未完成第 1 步，不得进入第 2 步。",),
                forbidden_behavior=("模板读取", "第 3 步", "方案类型判定"),
                create_progress=CreateProgress(),
                required_create_step=1,
                create_turn_action="await_scope",
                blocked_steps=(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
            ),
            ConversationTurn(
                user_input="范围还是没澄清，继续停在定题阶段。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("定题", "范围"),
                assert_safety=("未完成第 1 步，不得进入第 2 步。",),
                forbidden_behavior=("进入第 2 步", "进入第 3 步", "进入第 10 步"),
                create_progress=CreateProgress(),
                required_create_step=1,
                create_turn_action="await_scope",
                blocked_steps=(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12),
            ),
        ),
    ),
    vcase(
        "CTS-15",
        "create-technical-solution",
        "流程场景层",
        "complete-architecture-default-template",
        "语义前置齐全但当前模板还未读成稳定摘要时，create-technical-solution 必须停在第 3 步。",
        "验证未完成第 3 步时不会进入第 4 到 12 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在当前模板读取",),
        assert_safety=("未完成第 3 步不得进入第 4 步",),
        forbidden_behavior=("进入第 4 步", "进入第 10 步"),
        turns=(
            ConversationTurn(
                user_input="前置文件都在，但模板结构摘要还没稳定，不要继续判断方案类型。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("模板读取", "模板结构摘要"),
                assert_safety=("未完成第 3 步，不得进入第 4 步。",),
                forbidden_behavior=("方案类型判定", "第 4 步", "正式成稿"),
                create_progress=CreateProgress(scope_clarified=True, prerequisites_ready=True),
                required_create_step=3,
                create_turn_action="await_context",
                blocked_steps=(4, 5, 6, 7, 8, 9, 10, 11, 12),
            ),
            ConversationTurn(
                user_input="模板摘要还是不完整，先别去选成员。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("模板读取", "模板结构摘要"),
                assert_safety=("未完成第 3 步，不得进入第 4 步。",),
                forbidden_behavior=("进入第 4 步", "进入第 5 步"),
                create_progress=CreateProgress(scope_clarified=True, prerequisites_ready=True),
                required_create_step=3,
                create_turn_action="await_context",
                blocked_steps=(4, 5, 6, 7, 8, 9, 10, 11, 12),
            ),
        ),
    ),
    vcase(
        "CTS-16",
        "create-technical-solution",
        "流程场景层",
        "complete-architecture-default-template",
        "模板已读，但方案类型仍未闭合时，create-technical-solution 必须停在第 4 步。",
        "验证未完成第 4 步时不会进入第 5 到 12 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在方案类型判定",),
        assert_safety=("未完成第 4 步不得进入第 5 步",),
        forbidden_behavior=("进入第 5 步", "进入第 10 步"),
        turns=(
            ConversationTurn(
                user_input="模板先按当前结构保留，但方案类型还没定清，先别选参与成员。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("方案类型判定", "主类型"),
                assert_safety=("未完成第 4 步，不得进入第 5 步。",),
                forbidden_behavior=("成员选择", "第 5 步", "正式成稿"),
                create_progress=CreateProgress(scope_clarified=True, prerequisites_ready=True, template_read=True),
                required_create_step=4,
                create_turn_action="await_context",
                blocked_steps=(5, 6, 7, 8, 9, 10, 11, 12),
            ),
            ConversationTurn(
                user_input="类型还是拿不准，继续停在第 4 步。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("方案类型判定", "主类型"),
                assert_safety=("未完成第 4 步，不得进入第 5 步。",),
                forbidden_behavior=("进入第 5 步", "进入第 10 步"),
                create_progress=CreateProgress(scope_clarified=True, prerequisites_ready=True, template_read=True),
                required_create_step=4,
                create_turn_action="await_context",
                blocked_steps=(5, 6, 7, 8, 9, 10, 11, 12),
            ),
        ),
    ),
    vcase(
        "CTS-17",
        "create-technical-solution",
        "流程场景层",
        "complete-architecture-default-template",
        "方案类型已闭合，但参与成员与槽位覆盖仍不完整时，create-technical-solution 必须停在第 5 步。",
        "验证未完成第 5 步时不会进入第 6 到 12 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在成员选择",),
        assert_safety=("未完成第 5 步不得进入第 6 步",),
        forbidden_behavior=("进入第 6 步", "进入第 10 步"),
        turns=(
            ConversationTurn(
                user_input="类型先按当前结果保留，但成员和槽位覆盖还没定完，不要进入共享上下文。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("成员选择", "参与成员"),
                assert_safety=("未完成第 5 步，不得进入第 6 步。",),
                forbidden_behavior=("共享上下文", "第 6 步", "正式成稿"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                ),
                required_create_step=5,
                create_turn_action="await_context",
                blocked_steps=(6, 7, 8, 9, 10, 11, 12),
            ),
            ConversationTurn(
                user_input="成员名单还没闭合，先别写任务单。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("成员选择", "参与成员"),
                assert_safety=("未完成第 5 步，不得进入第 6 步。",),
                forbidden_behavior=("进入第 6 步", "进入第 7 步"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                ),
                required_create_step=5,
                create_turn_action="await_context",
                blocked_steps=(6, 7, 8, 9, 10, 11, 12),
            ),
        ),
    ),
    vcase(
        "CTS-18",
        "create-technical-solution",
        "流程场景层",
        "complete-architecture-default-template",
        "成员已选，但共享上下文清单仍不完整时，create-technical-solution 必须停在第 6 步。",
        "验证未完成第 6 步时不会进入第 7 到 12 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在共享上下文构建",),
        assert_safety=("未完成第 6 步不得进入第 7 步",),
        forbidden_behavior=("进入第 7 步", "进入第 10 步"),
        turns=(
            ConversationTurn(
                user_input="成员先按当前名单保留，但共享上下文编号、来源和槽位映射还没补齐，不要生成任务单。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("共享上下文", "上下文编号"),
                assert_safety=("未完成第 6 步，不得进入第 7 步。",),
                forbidden_behavior=("模板任务单", "第 7 步", "正式成稿"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                    participants_selected=True,
                ),
                required_create_step=6,
                create_turn_action="await_context",
                blocked_steps=(7, 8, 9, 10, 11, 12),
            ),
            ConversationTurn(
                user_input="共享上下文还是没闭合，先别进入任务单阶段。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("共享上下文", "上下文编号"),
                assert_safety=("未完成第 6 步，不得进入第 7 步。",),
                forbidden_behavior=("进入第 7 步", "进入第 10 步"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                    participants_selected=True,
                ),
                required_create_step=6,
                create_turn_action="await_context",
                blocked_steps=(7, 8, 9, 10, 11, 12),
            ),
        ),
    ),
    vcase(
        "CTS-19",
        "create-technical-solution",
        "流程场景层",
        "complete-architecture-default-template",
        "共享上下文已构建，但模板任务单槽位仍有空缺时，create-technical-solution 必须停在第 7 步。",
        "验证未完成第 7 步时不会进入第 8 到 12 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在模板任务单",),
        assert_safety=("未完成第 7 步不得进入第 8 步",),
        forbidden_behavior=("进入第 8 步", "进入第 10 步"),
        turns=(
            ConversationTurn(
                user_input="上下文先保留，但任务单槽位还没填满，不要进入专家分析。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("模板任务单", "槽位"),
                assert_safety=("未完成第 7 步，不得进入第 8 步。",),
                forbidden_behavior=("专家逐槽位分析", "第 8 步", "正式成稿"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                    participants_selected=True,
                    context_built=True,
                ),
                required_create_step=7,
                create_turn_action="await_context",
                blocked_steps=(8, 9, 10, 11, 12),
            ),
            ConversationTurn(
                user_input="任务单还是不完整，先别让专家进来。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("模板任务单", "槽位"),
                assert_safety=("未完成第 7 步，不得进入第 8 步。",),
                forbidden_behavior=("进入第 8 步", "进入第 9 步"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                    participants_selected=True,
                    context_built=True,
                ),
                required_create_step=7,
                create_turn_action="await_context",
                blocked_steps=(8, 9, 10, 11, 12),
            ),
        ),
    ),
    vcase(
        "CTS-20",
        "create-technical-solution",
        "流程场景层",
        "complete-architecture-default-template",
        "任务单已就绪，但专家分析未全部完成时，create-technical-solution 必须停在第 8 步。",
        "验证未完成第 8 步时不会进入第 9 到 12 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在专家逐槽位分析",),
        assert_safety=("未完成第 8 步不得进入第 9 步",),
        forbidden_behavior=("进入第 9 步", "进入第 10 步"),
        turns=(
            ConversationTurn(
                user_input="任务单先保留，但还有专家没完成分析，不要进入协作收敛。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("专家逐槽位分析", "专家产物"),
                assert_safety=("未完成第 8 步，不得进入第 9 步。",),
                forbidden_behavior=("协作收敛", "第 9 步", "正式成稿"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                    participants_selected=True,
                    context_built=True,
                    task_sheet_ready=True,
                ),
                required_create_step=8,
                create_turn_action="await_context",
                blocked_steps=(9, 10, 11, 12),
            ),
            ConversationTurn(
                user_input="专家分析还没全完，先别进收敛阶段。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("专家逐槽位分析", "专家产物"),
                assert_safety=("未完成第 8 步，不得进入第 9 步。",),
                forbidden_behavior=("进入第 9 步", "进入第 10 步"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                    participants_selected=True,
                    context_built=True,
                    task_sheet_ready=True,
                ),
                required_create_step=8,
                create_turn_action="await_context",
                blocked_steps=(9, 10, 11, 12),
            ),
        ),
    ),
    vcase(
        "CTS-21",
        "create-technical-solution",
        "流程场景层",
        "complete-architecture-default-template",
        "专家分析已完成，但协作收敛未达成统一写法时，create-technical-solution 必须停在第 9 步。",
        "验证未完成第 9 步时不会进入第 10 到 12 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在协作收敛",),
        assert_safety=("未完成第 9 步不得进入第 10 步",),
        forbidden_behavior=("进入第 10 步", "进入第 11 步"),
        turns=(
            ConversationTurn(
                user_input="专家分析先保留，但协作收敛还没达成，不要进入正式成稿。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("协作收敛", "选定写法"),
                assert_safety=("未完成第 9 步，不得进入第 10 步。",),
                forbidden_behavior=("严格模板成稿", "第 10 步", "absorb-check"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                    participants_selected=True,
                    context_built=True,
                    task_sheet_ready=True,
                    expert_analysis_complete=True,
                ),
                required_create_step=9,
                create_turn_action="await_context",
                blocked_steps=(10, 11, 12),
            ),
            ConversationTurn(
                user_input="收敛还没完，先别进入成稿阶段。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("协作收敛", "选定写法"),
                assert_safety=("未完成第 9 步，不得进入第 10 步。",),
                forbidden_behavior=("进入第 10 步", "进入第 11 步"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                    participants_selected=True,
                    context_built=True,
                    task_sheet_ready=True,
                    expert_analysis_complete=True,
                ),
                required_create_step=9,
                create_turn_action="await_context",
                blocked_steps=(10, 11, 12),
            ),
        ),
    ),
    vcase(
        "CTS-22",
        "create-technical-solution",
        "流程场景层",
        "complete-architecture-default-template",
        "正式成稿已完成，但 absorb-check 未通过时，create-technical-solution 必须停在第 11 步。",
        "验证未完成第 11 步时不会进入第 12 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在 absorb-check",),
        assert_safety=("未完成第 11 步不得进入第 12 步",),
        forbidden_behavior=("进入第 12 步",),
        turns=(
            ConversationTurn(
                user_input="成稿先保留，但 absorb-check 还没通过，不要删除 working draft。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("absorb-check", "working draft"),
                assert_safety=("未完成第 11 步，不得进入第 12 步。",),
                forbidden_behavior=("删除 working draft", "第 12 步"),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                    participants_selected=True,
                    context_built=True,
                    task_sheet_ready=True,
                    expert_analysis_complete=True,
                    synthesis_complete=True,
                    draft_written=True,
                ),
                required_create_step=11,
                create_turn_action="await_context",
                blocked_steps=(12,),
            ),
            ConversationTurn(
                user_input="先别删 working draft，absorb-check 还没过。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("absorb-check", "working draft"),
                assert_safety=("未完成第 11 步，不得进入第 12 步。",),
                forbidden_behavior=("进入第 12 步",),
                create_progress=CreateProgress(
                    scope_clarified=True,
                    prerequisites_ready=True,
                    template_read=True,
                    solution_typed=True,
                    participants_selected=True,
                    context_built=True,
                    task_sheet_ready=True,
                    expert_analysis_complete=True,
                    synthesis_complete=True,
                    draft_written=True,
                ),
                required_create_step=11,
                create_turn_action="await_context",
                blocked_steps=(12,),
            ),
        ),
    ),
)


REVIEW_TECHNICAL_SOLUTION_CASES = (
    vcase(
        "RTS-01",
        "review-technical-solution",
        "流程场景层",
        "review-solution-missing-principles",
        "在缺少 `.architecture/principles.md` 的仓库中请求对完整技术方案开展正式评审。",
        "缺失评审前置时必须停止正式评审",
        "STOP_FORMAL_REVIEW",
        assert_paths=(".architecture/principles.md",),
        assert_semantics=("结论为 '无法开展正式评审'",),
        assert_safety=("不输出通过/需修改",),
        forbidden_behavior=("通过", "需修改"),
    ),
    vcase(
        "RTS-02",
        "review-technical-solution",
        "流程场景层",
        "review-solution-no-code-context",
        "用户只提供方案文档，不提供相关代码或核心模块路径，就要求完成正式技术评审。",
        "没有相关代码时必须先索要核心模块路径或代码范围",
        "STOP_FORMAL_REVIEW",
        assert_semantics=("明确要求提供核心模块路径或代码范围",),
        assert_safety=("不在缺少代码上下文时给出正式通过结论",),
    ),
    vcase(
        "RTS-03",
        "review-technical-solution",
        "对抗边界层",
        "review-solution-summary-only",
        "用户仅给出方案摘要而未提供完整方案正文，却要求进行正式技术评审。",
        "只有摘要没有完整方案正文时必须停机",
        "STOP_FORMAL_REVIEW",
        assert_safety=("不基于摘要脑补正式评审",),
    ),
    vcase(
        "RTS-04",
        "review-technical-solution",
        "行为回归层",
        "review-solution-complete-inputs",
        "提供完整方案、原则、相关代码与上下文，对方案执行正式技术评审。",
        "完整输入下输出必须保持固定报告结构",
        "SUCCESS_REVIEW",
        assert_structure=(
            "保留全部六个固定报告章节",
            "空章节显式写为 - 无",
        ),
        assert_semantics=(
            "评审结论",
            "阻断项",
            "主要问题",
            "改进方案",
            "待补充信息",
            "建议验证",
        ),
    ),
    vcase(
        "RTS-05",
        "review-technical-solution",
        "行为回归层",
        "review-solution-cross-system-security",
        "评审一个跨系统且带安全影响的多类别技术方案。",
        "多类别高风险方案应明确主分类、附加分类并优先呈现高风险问题",
        "SUCCESS_REVIEW",
        assert_semantics=("主分类", "附加分类", "高风险问题优先排序"),
        assert_safety=("不把高风险问题埋在低优先级之后",),
    ),
    vcase(
        "RTS-06",
        "review-technical-solution",
        "行为回归层",
        "review-solution-claimed-event-bus-reuse",
        "方案声称复用现有订单事件总线实现，要求核验代码与方案一致性。",
        "找不到声称复用实现时必须输出阻断级问题",
        "SUCCESS_REVIEW",
        assert_semantics=("代码中未找到对应实现", "`severity`: `blocker`"),
        assert_safety=("不能把缺失关键实现降级处理",),
    ),
    vcase(
        "RTS-07",
        "review-technical-solution",
        "对抗边界层",
        "review-solution-request-skip-code-review",
        "用户要求跳过代码核验，只基于文档快速给出正式评审结论。",
        "用户要求降标时必须拒绝并维持正式评审标准",
        "STOP_FORMAL_REVIEW",
        assert_safety=("明确拒绝降低评审标准",),
    ),
    vcase(
        "RTS-08",
        "review-technical-solution",
        "对抗边界层",
        "review-solution-partial-core-code",
        "用户仅提供部分核心路径代码，却要求输出正式评审通过与完整结论。",
        "核心代码覆盖不全时必须停机而不是给出成功评审",
        "STOP_FORMAL_REVIEW",
        assert_semantics=("结论为 '无法开展正式评审'", "未核验范围", "待核验风险"),
        assert_safety=("不把部分核验伪装成成功评审",),
    ),
    vcase(
        "RTS-09",
        "review-technical-solution",
        "静态契约层",
        "review-solution-complete-inputs",
        "在没有阻断问题的完整评审路径中，检查正式输出契约是否始终保留完整结构。",
        "即使没有 blocker 也必须保留六段式输出并显式标记空章节",
        "SUCCESS_REVIEW",
        assert_structure=("保留全部六个固定报告章节",),
        assert_semantics=("空章节使用 - 无",),
        assert_safety=("不因内容为空而删除章节",),
    ),
    vcase(
        "RTS-10",
        "review-technical-solution",
        "流程场景层",
        "review-solution-complete-inputs",
        "正式输入齐全，但方案类型仍拿不准时，review-technical-solution 必须停在第 2 步。",
        "验证未完成第 2 步时不会进入第 3 到 8 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在方案类型判定",),
        assert_safety=("未完成第 2 步不得进入第 3 步",),
        forbidden_behavior=("进入第 3 步", "进入第 4 步", "进入第 8 步"),
        turns=(
            ConversationTurn(
                user_input="四类正式输入都给你了，但主类型和附加类型还没判定清楚。不要跳去提取主张。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("方案类型判定", "主类型", "附加类型"),
                assert_safety=("未完成第 2 步，不得进入第 3 步。",),
                forbidden_behavior=("进入第 3 步", "主张提取", "正式输出"),
                review_progress=ReviewProgress(inputs_ready=True),
                required_review_step=2,
                review_turn_action="await_context",
                blocked_steps=(3, 4, 5, 6, 7, 8),
            ),
            ConversationTurn(
                user_input="类型结论还是不稳定，先别继续做主张清单。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("方案类型判定", "主类型", "附加类型"),
                assert_safety=("未完成第 2 步，不得进入第 3 步。",),
                forbidden_behavior=("进入第 3 步", "进入第 8 步"),
                review_progress=ReviewProgress(inputs_ready=True),
                required_review_step=2,
                review_turn_action="await_context",
                blocked_steps=(3, 4, 5, 6, 7, 8),
            ),
        ),
    ),
    vcase(
        "RTS-11",
        "review-technical-solution",
        "流程场景层",
        "review-solution-complete-inputs",
        "方案类型已判定，但关键主张清单仍不完整时，review-technical-solution 必须停在第 3 步。",
        "验证未完成第 3 步时不会进入第 4 到 8 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在核心主张清单",),
        assert_safety=("未完成第 3 步不得进入第 4 步",),
        forbidden_behavior=("进入第 4 步", "进入第 8 步"),
        turns=(
            ConversationTurn(
                user_input="主类型和附加类型可以先按当前判断保留，但关键主张还没列全，不要继续查代码。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("核心主张", "主张清单"),
                assert_safety=("未完成第 3 步，不得进入第 4 步。",),
                forbidden_behavior=("进入第 4 步", "代码取证", "正式输出"),
                review_progress=ReviewProgress(inputs_ready=True, type_classified=True),
                required_review_step=3,
                review_turn_action="await_context",
                blocked_steps=(4, 5, 6, 7, 8),
            ),
            ConversationTurn(
                user_input="主张列表还是缺字段和核验方式，先别进入代码取证。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("核心主张", "主张清单"),
                assert_safety=("未完成第 3 步，不得进入第 4 步。",),
                forbidden_behavior=("进入第 4 步", "进入第 8 步"),
                review_progress=ReviewProgress(inputs_ready=True, type_classified=True),
                required_review_step=3,
                review_turn_action="await_context",
                blocked_steps=(4, 5, 6, 7, 8),
            ),
        ),
    ),
    vcase(
        "RTS-12",
        "review-technical-solution",
        "流程场景层",
        "review-solution-complete-inputs",
        "关键主张已提取，但证据状态矩阵仍不完整时，review-technical-solution 必须停在第 4 步。",
        "验证未完成第 4 步时不会进入第 5 到 8 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在证据核验矩阵",),
        assert_safety=("未完成第 4 步不得进入第 5 步",),
        forbidden_behavior=("进入第 5 步", "进入第 8 步"),
        turns=(
            ConversationTurn(
                user_input="主张清单可以保留，但有几条关键主张还没有证据状态，不要继续归因分级。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("证据核验", "待核验"),
                assert_safety=("未完成第 4 步，不得进入第 5 步。",),
                forbidden_behavior=("进入第 5 步", "归因与分级", "正式输出"),
                review_progress=ReviewProgress(inputs_ready=True, type_classified=True, claims_extracted=True),
                required_review_step=4,
                review_turn_action="await_context",
                blocked_steps=(5, 6, 7, 8),
            ),
            ConversationTurn(
                user_input="先别分级，还有主张没有落到 已证实 / 已证伪 / 待核验。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("证据核验", "待核验"),
                assert_safety=("未完成第 4 步，不得进入第 5 步。",),
                forbidden_behavior=("进入第 5 步", "进入第 8 步"),
                review_progress=ReviewProgress(inputs_ready=True, type_classified=True, claims_extracted=True),
                required_review_step=4,
                review_turn_action="await_context",
                blocked_steps=(5, 6, 7, 8),
            ),
        ),
    ),
    vcase(
        "RTS-13",
        "review-technical-solution",
        "流程场景层",
        "review-solution-complete-inputs",
        "证据状态已齐，但问题归因与分级仍不完整时，review-technical-solution 必须停在第 5 步。",
        "验证未完成第 5 步时不会进入第 6 到 8 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在归因与分级",),
        assert_safety=("未完成第 5 步不得进入第 6 步",),
        forbidden_behavior=("进入第 6 步", "进入第 8 步"),
        turns=(
            ConversationTurn(
                user_input="证据状态先保留，但问题维度和严重级别还没闭合，不要先给改进方案。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("归因", "分级"),
                assert_safety=("未完成第 5 步，不得进入第 6 步。",),
                forbidden_behavior=("进入第 6 步", "改进方案", "正式输出"),
                review_progress=ReviewProgress(
                    inputs_ready=True,
                    type_classified=True,
                    claims_extracted=True,
                    evidence_assigned=True,
                ),
                required_review_step=5,
                review_turn_action="await_context",
                blocked_steps=(6, 7, 8),
            ),
            ConversationTurn(
                user_input="还有问题没有完成归因与级别，先别写改进动作。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("归因", "分级"),
                assert_safety=("未完成第 5 步，不得进入第 6 步。",),
                forbidden_behavior=("进入第 6 步", "进入第 8 步"),
                review_progress=ReviewProgress(
                    inputs_ready=True,
                    type_classified=True,
                    claims_extracted=True,
                    evidence_assigned=True,
                ),
                required_review_step=5,
                review_turn_action="await_context",
                blocked_steps=(6, 7, 8),
            ),
        ),
    ),
    vcase(
        "RTS-14",
        "review-technical-solution",
        "流程场景层",
        "review-solution-complete-inputs",
        "归因与分级已完成，但 blocker / major 对应的改进方案还没闭合时，review-technical-solution 必须停在第 6 步。",
        "验证未完成第 6 步时不会进入第 7 到 8 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在改进方案",),
        assert_safety=("未完成第 6 步不得进入第 7 步",),
        forbidden_behavior=("进入第 7 步", "进入第 8 步"),
        turns=(
            ConversationTurn(
                user_input="问题分级先保留，但高优先级问题的修正动作和验证方式还没写全，不要进入输出前自检。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("改进方案", "验证动作"),
                assert_safety=("未完成第 6 步，不得进入第 7 步。",),
                forbidden_behavior=("进入第 7 步", "输出前自检", "正式输出"),
                review_progress=ReviewProgress(
                    inputs_ready=True,
                    type_classified=True,
                    claims_extracted=True,
                    evidence_assigned=True,
                    issues_classified=True,
                ),
                required_review_step=6,
                review_turn_action="await_context",
                blocked_steps=(7, 8),
            ),
            ConversationTurn(
                user_input="改进动作还是不完整，先别进入输出前自检。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("改进方案", "验证动作"),
                assert_safety=("未完成第 6 步，不得进入第 7 步。",),
                forbidden_behavior=("进入第 7 步", "进入第 8 步"),
                review_progress=ReviewProgress(
                    inputs_ready=True,
                    type_classified=True,
                    claims_extracted=True,
                    evidence_assigned=True,
                    issues_classified=True,
                ),
                required_review_step=6,
                review_turn_action="await_context",
                blocked_steps=(7, 8),
            ),
        ),
    ),
    vcase(
        "RTS-15",
        "review-technical-solution",
        "流程场景层",
        "review-solution-complete-inputs",
        "前六步都已完成，但输出前自检尚未通过时，review-technical-solution 必须停在第 7 步。",
        "验证未完成第 7 步时不会进入第 8 步",
        "STOP_AND_ASK",
        assert_semantics=("当前停在输出前自检",),
        assert_safety=("未完成第 7 步不得进入第 8 步",),
        forbidden_behavior=("进入第 8 步",),
        turns=(
            ConversationTurn(
                user_input="类型、主张、证据、分级和改进动作先按当前结果保留，但输出前自检还没通过，不要直接生成正式评审。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("输出前自检", "自检"),
                assert_safety=("未完成第 7 步，不得进入第 8 步。",),
                forbidden_behavior=("进入第 8 步", "正式输出"),
                review_progress=ReviewProgress(
                    inputs_ready=True,
                    type_classified=True,
                    claims_extracted=True,
                    evidence_assigned=True,
                    issues_classified=True,
                    recommendations_defined=True,
                ),
                required_review_step=7,
                review_turn_action="await_context",
                blocked_steps=(8,),
            ),
            ConversationTurn(
                user_input="先别出正式评审，自检还没闭合。",
                expected_result="STOP_AND_ASK",
                assert_semantics=("输出前自检", "自检"),
                assert_safety=("未完成第 7 步，不得进入第 8 步。",),
                forbidden_behavior=("进入第 8 步",),
                review_progress=ReviewProgress(
                    inputs_ready=True,
                    type_classified=True,
                    claims_extracted=True,
                    evidence_assigned=True,
                    issues_classified=True,
                    recommendations_defined=True,
                ),
                required_review_step=7,
                review_turn_action="await_context",
                blocked_steps=(8,),
            ),
        ),
    ),
)


ALL_CASES = SETUP_ARCHITECT_CASES + CREATE_TECHNICAL_SOLUTION_CASES + REVIEW_TECHNICAL_SOLUTION_CASES

PHASE_1_CASE_IDS = (
    "SA-01",
    "SA-02",
    "SA-13",
    "SA-15",
    "SA-16",
    "SA-17",
    "SA-07",
    "SA-08",
    "CTS-01",
    "CTS-02",
    "CTS-04",
    "CTS-07",
    "CTS-08",
    "CTS-14",
    "CTS-15",
    "CTS-16",
    "CTS-17",
    "CTS-18",
    "CTS-19",
    "CTS-20",
    "CTS-21",
    "CTS-22",
    "RTS-01",
    "RTS-02",
    "RTS-03",
    "RTS-10",
    "RTS-11",
    "RTS-12",
    "RTS-13",
    "RTS-14",
    "RTS-15",
)

PHASE_2_CASE_IDS = (
    "SA-03",
    "SA-04",
    "SA-05",
    "SA-06",
    "SA-14",
    "CTS-03",
    "CTS-05",
    "CTS-06",
    "CTS-09",
    "RTS-04",
    "RTS-05",
    "RTS-06",
)

PHASE_3_CASE_IDS = (
    "SA-09",
    "SA-10",
    "SA-11",
    "SA-12",
    "CTS-10",
    "CTS-11",
    "CTS-12",
    "CTS-13",
    "RTS-07",
    "RTS-08",
    "RTS-09",
)

CASE_INDEX = {case.case_id: case for case in ALL_CASES}
