from dataclasses import dataclass
from typing import Tuple


@dataclass(frozen=True)
class ValidationCase:
    case_id: str
    skill: str
    layer: str
    fixture: str
    prompt: str
    purpose: str
    expected_result: str
    assert_paths: Tuple[str, ...] = ()
    assert_structure: Tuple[str, ...] = ()
    assert_semantics: Tuple[str, ...] = ()
    assert_safety: Tuple[str, ...] = ()
    forbidden_behavior: Tuple[str, ...] = ()


def vcase(
    case_id: str,
    skill: str,
    layer: str,
    fixture: str,
    prompt: str,
    purpose: str,
    expected_result: str,
    *,
    assert_paths: Tuple[str, ...] = (),
    assert_structure: Tuple[str, ...] = (),
    assert_semantics: Tuple[str, ...] = (),
    assert_safety: Tuple[str, ...] = (),
    forbidden_behavior: Tuple[str, ...] = (),
) -> ValidationCase:
    return ValidationCase(
        case_id=case_id,
        skill=skill,
        layer=layer,
        fixture=fixture,
        prompt=prompt,
        purpose=purpose,
        expected_result=expected_result,
        assert_paths=assert_paths,
        assert_structure=assert_structure,
        assert_semantics=assert_semantics,
        assert_safety=assert_safety,
        forbidden_behavior=forbidden_behavior,
    )


SETUP_ARCHITECT_CASES = (
    vcase(
        "SA-01",
        "setup-architect",
        "流程场景层",
        "empty-project",
        "在空仓库中请求执行 setup-architect 初始化默认架构框架。",
        "锁定最基础的 setup 成功路径",
        "SUCCESS_INIT",
        assert_paths=(
            ".architecture/technical-solutions/",
            ".architecture/templates/",
            ".architecture/templates/technical-solution-template.md",
            ".architecture/members.yml",
            ".architecture/principles.md",
        ),
        assert_structure=(".architecture 最小结构完整",),
        assert_safety=("只创建最小必需结构",),
        forbidden_behavior=("写入 legacy 路径",),
    ),
    vcase(
        "SA-02",
        "setup-architect",
        "流程场景层",
        "complete-architecture-default-template",
        "在已完成初始化的仓库中再次请求执行 setup-architect 完整安装流程。",
        "防止重复 setup 产生重复目录和副产物",
        "SUCCESS_INIT",
        assert_paths=(".architecture/",),
        assert_structure=("不生成 .architecture/.architecture", "不生成重复模板"),
        assert_safety=("不引入 legacy 或临时副产物",),
        forbidden_behavior=("嵌套 .architecture", "重复模板副本"),
    ),
    vcase(
        "SA-03",
        "setup-architect",
        "行为回归层",
        "partial-architecture-missing-one-file",
        "在只缺少一个必需文件的已部分初始化仓库中请求补齐 setup。",
        "只补缺失项，不覆盖已有项",
        "SUCCESS_INIT",
        assert_paths=(
            ".architecture/members.yml",
            ".architecture/principles.md",
            ".architecture/templates/technical-solution-template.md",
        ),
        assert_structure=("现有文件保持原位",),
        assert_safety=("仅补齐缺失的单个前置文件，已有内容不被无提示覆盖",),
        forbidden_behavior=("重写无缺失文件",),
    ),
    vcase(
        "SA-04",
        "setup-architect",
        "行为回归层",
        "complete-architecture-default-template",
        "初始化流程询问模板定制时，用户明确回答保留当前模板。",
        "用户拒绝定制模板时保留当前模板",
        "SUCCESS_INIT",
        assert_paths=(".architecture/templates/technical-solution-template.md",),
        assert_structure=("模板路径不变",),
        assert_semantics=("模板最终状态明确为保留当前模板",),
        assert_safety=("不发生模板替换",),
        forbidden_behavior=("无用户请求时覆盖模板",),
    ),
    vcase(
        "SA-05",
        "setup-architect",
        "行为回归层",
        "template-replacement-inputs",
        "完整初始化结束后，用户提供完整 Markdown 模板并要求替换当前模板。",
        "初始化尾声允许整文件替换模板",
        "SUCCESS_REPLACE_TEMPLATE",
        assert_paths=(".architecture/templates/technical-solution-template.md",),
        assert_structure=("整体替换单个目标文件",),
        assert_safety=("不做局部 merge",),
        forbidden_behavior=("局部编辑", "内容合并"),
    ),
    vcase(
        "SA-06",
        "setup-architect",
        "行为回归层",
        "complete-architecture-default-template",
        "安装完成后单独请求替换 `.architecture/templates/technical-solution-template.md`。",
        "安装后仅替换模板时跳过完整 setup",
        "SUCCESS_REPLACE_TEMPLATE",
        assert_paths=(".architecture/templates/technical-solution-template.md",),
        assert_structure=("只走模板替换分支",),
        assert_safety=("不重跑初始化流程",),
        forbidden_behavior=("重新安装 .architecture 基础结构",),
    ),
    vcase(
        "SA-07",
        "setup-architect",
        "对抗边界层",
        "partial-architecture-missing-one-file",
        "在缺少模板目录、模板文件、成员文件或原则文件之一时，请求只执行模板替换分支。",
        "模板替换前置不满足时必须停机",
        "STOP_AND_REDIRECT",
        assert_paths=(
            ".architecture/templates/",
            ".architecture/templates/technical-solution-template.md",
            ".architecture/members.yml",
            ".architecture/principles.md",
        ),
        assert_semantics=("响应明确点名缺失的前置路径",),
        assert_safety=("要求先完成完整 setup", "不静默补文件"),
        forbidden_behavior=("边补环境边替换模板",),
    ),
    vcase(
        "SA-08",
        "setup-architect",
        "对抗边界层",
        "template-replacement-inputs",
        "用户仅提供模板片段、patch 或口头描述并要求替换技术方案模板。",
        "拒绝模板片段和口头描述输入",
        "STOP_AND_ASK",
        assert_semantics=("继续索要完整 Markdown、路径或链接",),
        assert_safety=("不自动生成模板", "不做局部编辑", "不做内容合并"),
        forbidden_behavior=("根据片段脑补完整模板",),
    ),
    vcase(
        "SA-09",
        "setup-architect",
        "行为回归层",
        "complete-architecture-default-template",
        "用户请求自定义成员配置，并尝试加入新的专家角色。",
        "成员定制必须保留核心成员",
        "SUCCESS_INIT",
        assert_semantics=(
            "保留系统架构师",
            "保留领域专家",
            "保留安全专家",
            "保留性能专家",
            "保留可维护性专家",
        ),
        assert_safety=("允许增补专家，不允许替换核心成员",),
        forbidden_behavior=("删除核心成员",),
    ),
    vcase(
        "SA-10",
        "setup-architect",
        "行为回归层",
        "complete-architecture-default-template",
        "用户请求自定义架构原则，并希望调整团队的评审与决策准则。",
        "原则定制必须保留核心原则和最低覆盖范围",
        "SUCCESS_INIT",
        assert_semantics=(
            "保留核心原则",
            "覆盖模块边界与依赖方向",
            "覆盖 API / 事件 / 数据边界",
            "覆盖测试和验证基线",
            "覆盖安全与合规底线",
            "覆盖技术方案和实施计划的决策标准",
        ),
        assert_safety=("不删除核心原则",),
        forbidden_behavior=("删除核心原则",),
    ),
    vcase(
        "SA-11",
        "setup-architect",
        "静态契约层",
        "complete-architecture-default-template",
        "setup-architect 完成初始化并准备输出最终总结。",
        "最终总结前结构必须已验证",
        "SUCCESS_INIT",
        assert_paths=(
            ".architecture/technical-solutions/",
            ".architecture/templates/",
            ".architecture/templates/technical-solution-template.md",
            ".architecture/members.yml",
            ".architecture/principles.md",
        ),
        assert_safety=("无 legacy 目录",),
        forbidden_behavior=(
            "保留 .architecture/solutions",
            ".architecture/plans",
            ".architecture/reviews",
        ),
    ),
    vcase(
        "SA-12",
        "setup-architect",
        "静态契约层",
        "empty-project",
        "在空仓库中执行 setup-architect，检查初始化过程是否引入无关文件或目录。",
        "安装和初始化不应引入无关产物",
        "SUCCESS_INIT",
        assert_structure=("assistant 目标目录唯一",),
        assert_safety=("无 CLAUDE.md", "无 agent_docs", "无嵌套 .git", "无随机 temp 目录"),
        forbidden_behavior=("生成无关安装副产物",),
    ),
)


CREATE_TECHNICAL_SOLUTION_CASES = (
    vcase(
        "CTS-01",
        "create-technical-solution",
        "流程场景层",
        "empty-project",
        "在没有 `.architecture/` 前置的空仓库中直接请求创建技术方案。",
        "前置全缺失时立即停止并回指 setup-architect",
        "STOP_AND_REDIRECT",
        assert_paths=(
            ".architecture/members.yml",
            ".architecture/principles.md",
            ".architecture/templates/technical-solution-template.md",
        ),
        assert_semantics=("响应明确列出全部缺失前置并回指 setup-architect",),
        assert_safety=("不自动创建 .architecture/*", "不继续生成技术方案"),
        forbidden_behavior=("伪造初始化产物",),
    ),
    vcase(
        "CTS-02",
        "create-technical-solution",
        "流程场景层",
        "partial-architecture-missing-one-file",
        "在只缺少一个关键前置文件的仓库中请求创建技术方案。",
        "任一关键前置缺失都必须停机",
        "STOP_AND_REDIRECT",
        assert_paths=(
            ".architecture/members.yml",
            ".architecture/principles.md",
            ".architecture/templates/technical-solution-template.md",
        ),
        assert_safety=("不允许半继续执行",),
        forbidden_behavior=("跳过缺失项继续生成",),
    ),
    vcase(
        "CTS-03",
        "create-technical-solution",
        "行为回归层",
        "complete-architecture-default-template",
        "在默认模板和前置完整的仓库中，为“payment pipeline rework”创建技术方案。",
        "标准成功路径把结果写到正式目录",
        "SUCCESS_CREATE",
        assert_paths=(".architecture/technical-solutions/payment-pipeline-rework.md",),
        assert_structure=("生成正式技术方案文档",),
        assert_safety=("不写入其他目录",),
        forbidden_behavior=("输出聊天式说明替代文档",),
    ),
    vcase(
        "CTS-04",
        "create-technical-solution",
        "行为回归层",
        "complete-architecture-custom-template",
        "在自定义模板已安装的仓库中，为同一主题创建技术方案。",
        "结果必须遵循当前自定义模板，而不是默认模板",
        "SUCCESS_CREATE",
        assert_structure=("保留当前模板顶层结构",),
        assert_semantics=("先读取当前模板",),
        assert_safety=("不回退默认模板结构",),
        forbidden_behavior=("发明默认顶层章节",),
    ),
    vcase(
        "CTS-05",
        "create-technical-solution",
        "行为回归层",
        "complete-architecture-custom-template",
        "在自定义模板场景下生成技术方案，并包含需要展开的小节和表格内容。",
        "允许加小节但禁止新增模板外一级章节",
        "SUCCESS_CREATE",
        assert_structure=("一级结构保持不变",),
        assert_safety=("只在现有章节内细化",),
        forbidden_behavior=("新增用户模板没有定义的一级章节",),
    ),
    vcase(
        "CTS-06",
        "create-technical-solution",
        "行为回归层",
        "complete-architecture-default-template",
        "在默认模板场景下生成正式技术方案，并提供足够上下文覆盖所有必填信息块。",
        "所有必填信息块都必须被覆盖",
        "SUCCESS_CREATE",
        assert_semantics=(
            "问题与背景",
            "目标与非目标",
            "约束与依赖",
            "推荐方案",
            "备选方案与权衡",
            "详细设计",
            "风险与缓解",
            "实施建议",
            "评审关注点",
            "未决问题",
        ),
        assert_safety=("不遗漏强制信息块",),
        forbidden_behavior=("只输出零散结论",),
    ),
    vcase(
        "CTS-07",
        "create-technical-solution",
        "对抗边界层",
        "complete-architecture-custom-template",
        "在结构明显不足的自定义模板下请求生成技术方案。",
        "模板无法安全承载信息块时必须停下来询问",
        "STOP_AND_ASK",
        assert_semantics=("明确说明无法安全落位的信息块",),
        assert_safety=("不擅自新增一级章节",),
        forbidden_behavior=("猜测模板语义继续生成",),
    ),
    vcase(
        "CTS-08",
        "create-technical-solution",
        "对抗边界层",
        "existing-solution-file",
        "当 `.architecture/technical-solutions/payment-pipeline-rework.md` 已存在时再次请求生成同主题方案。",
        "目标文件已存在时必须先确认覆盖或另存",
        "STOP_AND_ASK",
        assert_paths=(".architecture/technical-solutions/payment-pipeline-rework.md",),
        assert_safety=("没有未经确认覆盖已有文件",),
        forbidden_behavior=("静默覆盖既有文档",),
    ),
    vcase(
        "CTS-09",
        "create-technical-solution",
        "行为回归层",
        "existing-solution-file",
        "已有同名目标文件时，用户明确拒绝覆盖并要求保留现有文档。",
        "用户拒绝覆盖时保留原文件并等待另存决策",
        "SUCCESS_SAVE_AS",
        assert_paths=(".architecture/technical-solutions/payment-pipeline-rework.md",),
        assert_safety=("原文件内容保持不变，且停止覆盖原文件",),
        forbidden_behavior=("继续写回原路径",),
    ),
    vcase(
        "CTS-10",
        "create-technical-solution",
        "对抗边界层",
        "complete-architecture-default-template",
        "主题同时命中多个 solution type 时请求生成技术方案。",
        "多类型主题按成员并集参与，且始终包含系统架构师",
        "SUCCESS_CREATE",
        assert_semantics=("成员取并集并去重", "系统架构师始终参与"),
        assert_safety=("不遗漏高风险主题所需成员",),
        forbidden_behavior=("只按单一类型裁剪成员",),
    ),
    vcase(
        "CTS-11",
        "create-technical-solution",
        "流程场景层",
        "complete-architecture-default-template",
        "在未刚执行 setup-architect 的独立会话中，基于已存在前置直接请求创建技术方案。",
        "前置齐全时应能独立执行，不依赖刚跑过 setup",
        "SUCCESS_CREATE",
        assert_paths=(".architecture/technical-solutions/payment-pipeline-rework.md",),
        assert_semantics=("仅依赖既有 .architecture 契约",),
        assert_safety=("不要求 setup 继续参与",),
        forbidden_behavior=("回头猜安装过程上下文",),
    ),
    vcase(
        "CTS-12",
        "create-technical-solution",
        "对抗边界层",
        "partial-architecture-missing-one-file",
        "关键前置不完整时，诱导 skill 一边补环境一边生成技术方案。",
        "前置不完整时不得脑补成员、原则或模板",
        "STOP_AND_REDIRECT",
        assert_safety=("不边补环境边写 solution",),
        forbidden_behavior=("伪造 members.yml", "伪造 principles.md", "伪造模板文件"),
    ),
)


ALL_CASES = SETUP_ARCHITECT_CASES + CREATE_TECHNICAL_SOLUTION_CASES

PHASE_1_CASE_IDS = (
    "SA-01",
    "SA-02",
    "SA-07",
    "SA-08",
    "CTS-01",
    "CTS-02",
    "CTS-04",
    "CTS-07",
    "CTS-08",
)

PHASE_2_CASE_IDS = (
    "SA-03",
    "SA-04",
    "SA-05",
    "SA-06",
    "CTS-03",
    "CTS-05",
    "CTS-06",
    "CTS-09",
)

PHASE_3_CASE_IDS = (
    "SA-09",
    "SA-10",
    "SA-11",
    "SA-12",
    "CTS-10",
    "CTS-11",
    "CTS-12",
)

CASE_INDEX = {case.case_id: case for case in ALL_CASES}
